### ISSUE TITLE
Error on run

### ISSUE THREAD

**Issue by Avrution** [Unjust-Harry/FancyScreenPatchForRecettear#1]
This is with Windows 10

`The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
At line:1 char:1
+ .\Install-FancyScreenPatchForRecettear.v1_0_0.FromBatchFile.ps1
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException`

Installing Powershell 7.3 lets me run things, but not with 5.1

**Comment by just-harry** [comment]
Mmm, that's not good. Thanks for the report :)

If I'm understanding this correctly, the script fails with that error at start-up, and doesn't run at all?
If that's the case, I've been investigating this for a bit, and I'm stumped as to what could be causing it.

I've two questions:
1. If you right-click the `Install-FancyScreenPatchForRecettear.v1_0_0.FromBatchFile.ps1` file, and select the "Run with PowerShell" option, does the script run successfully?
2. Does the path that the `Install-FancyScreenPatchForRecettear.bat` file is in have any apostrophes in it?

Lastly, I've put together a quick change to the Batch wrapper that invokes the script slightly differently, does it work for you? Find it here: https://github.com/Unjust-Harry/FancyScreenPatchForRecettear/blob/1.0.1-testing/Install-FancyScreenPatchForRecettear.v1.0.1-testing.bat

**Comment by Avrution** [comment]
~No apostrophes in the path.~ I was incorrect on this.  The path GOG installs to does have an apostrophe, which it seems 5.1 can't handle.

Renaming the directory does solve this issue.

**Comment by just-harry** [comment]
Thanks for the assistance in troubleshooting this.

What an annoying bug on PowerShell's end – I'll put in a workaround for it, at some point.
