### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by ghost** [Unjust-Harry/FancyScreenPatchForRecettear#5]
I am getting this error when trying to apply the patch. Also, I get the following error in powershell:

```
Cannot convert value "-1" to type "System.UInt32". Error: "Value was either too large or too small for a UInt32."
At C:\Users\USERNAME\Desktop\Install-FancyScreenPatchForRecettear.v1_0_2.FromBatchFile.ps1:6799 char:5
+ ...             ${@IncrementSelectedSaveSlotPulsatingEffectCounter} = [UI ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidCastIConvertible
```

**Comment by just-harry** [comment]
Hi—huh, that would indicate that the script is failing to find some code in the game's executable. May I ask which version of the game you're trying to patch (as in the language, the version-number, and the storefront it was acquired from)? Also, what operating-system are you running the script on?

**Comment by ghost** [comment]
I am using the steam version. Windows 10.

Edit: I got it working. It still gives the "TypeError: Failed to fetch" message.
